-- AlterTable
ALTER TABLE "assets" ADD COLUMN     "address" TEXT,
ADD COLUMN     "area_sqft" INTEGER,
ADD COLUMN     "bathrooms" DOUBLE PRECISION,
ADD COLUMN     "bedrooms" INTEGER,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "city_mpg" INTEGER,
ADD COLUMN     "combination_mpg" INTEGER,
ADD COLUMN     "cylinders" INTEGER,
ADD COLUMN     "displacement" DOUBLE PRECISION,
ADD COLUMN     "drive" TEXT,
ADD COLUMN     "garage" INTEGER,
ADD COLUMN     "has_pool" BOOLEAN,
ADD COLUMN     "highway_mpg" INTEGER,
ADD COLUMN     "listing_status" TEXT,
ADD COLUMN     "price" DECIMAL(65,30) DEFAULT 0,
ADD COLUMN     "property_type" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "vehicle_class" TEXT,
ADD COLUMN     "year_built" INTEGER,
ADD COLUMN     "zip_code" TEXT;
